### ISSUE TITLE
Frame acquisition hangs after setting ROI

### ISSUE THREAD

**Issue by dmyersturnbull** [jordens/pydc1394#3]
On our Allied Vision [Pike 145B](https://cdn.alliedvision.com/fileadmin/content/documents/products/cameras/Pike/techman/Pike_TechMan_en.pdf), we can capture still frames in format 0, mode 7 using `Camera.start_one_shot` and `Camera.dequeue(poll=True)`.

However, setting `image_size = (4*100, 2*100)` where the width and height are multiples of their respective units and less than `max_image_size`, `Camera.dequeue(poll=True)` hangs permanently.

`Camera.dequeue` also hangs if we use `start_video` or `start_multi_shot`, even if we don't set the ROI.

**Comment by jordens** [comment]
Hmm. It is a bit unlikely that this is is a *py*dc1394 problem. My guess would be that this is also in bare dc1394 or/and the format being invalid or requiring a different triggering mode (maybe a hardware trigger).

**Comment by jordens** [comment]
Is this resolved?
