### ISSUE TITLE
Format7 error 

### ISSUE THREAD

**Issue by eghbalhosseini** [jordens/pydc1394#5]
Hi 
I am trying to capture at high rate(>100Hz) on point grey grasshopper. My understanding is that I need to change FORMAT7 packet size to do that. but I am running to the following issue: 

from pydc1394 import Camera, Camera2, Format7, Mode
cam=camera2.Camera()
camprp=Format7(cam,7)

ArgumentError                             Traceback (most recent call last)
<ipython-input-71-368ad6e96634> in <module>()
      1 cam=camera2.Camera()
      2 camprp=Format7(cam,7)
----> 3 camprp.color_coding

/Library/Python/2.7/site-packages/pydc1394-2.0-py2.7.egg/pydc1394/camera2.pyc in color_coding(self)
    777         cc = color_coding_t()
    778         dll.dc1394_format7_get_color_coding(
--> 779                 self._cam, self._mode_id, byref(cc))
    780         return color_coding_vals[cc.value]
    781 

**ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_camera_t instance instead of Camera**

I can't tell if it is due to how I define Format7 instance or something else. 

Thanks, 
Eghbal

**Comment by jordens** [comment]
As the documentation says:
https://github.com/jordens/pydc1394/blob/master/pydc1394/camera2.py#L586
